info:
  version: "@project.version@"
spring:
  application:
    name: "@project.artifactId@"
#  zipkin:
#    locator:
#      discovery:
#        enabled: true
#    service:
#      name: lux-tracker
###MQ用来处理zipkin日志追踪
  rabbitmq:
    host: 192.168.113.18
    port: 35672
    username: admin
    password: Rabbit_fy_123
    virtual-host: /
  cloud:
    config:
      enabled: true
    consul:
      host: 192.168.113.18
      port: 8500
      discovery:
        #tags: management.context-path=/foo, health.path=/ping
        health-check-interval: 10s
        health-check-timeout: 1s
        ##health-check-url: http://lucius:123456@org-lucius-commons-service-tracker:8080/health
        prefer-ip-address: true
#management.context-path: /foo
#endpoints.health.path: /ping
  boot:
    admin:
      routes:
        endpoints:
        - env
        - metrics
        - dump
        - jolokia
        - info
        - configprops
        - trace
        - logfile
        - refresh
        - flyway
        - liquibase
        - heapdump
        - loggers
        - auditevents
        - hystrix.stream
      turbine:
        clusters:
        - default
        location: fy-monitor              ##指向我们定义的turbine server，这里本应用也是一个turbine server
spring.boot.admin.discovery:
  ignored-services: consul,lux-monitor,lux-monitor     ##不监控consul和自己本身
turbine: ##定义自己本身是一个turbine server
  aggregator:
    clusterConfig: default   # 指定聚合哪些集群，多个使用","分割，默认为default。可使用http://.../turbine.stream?cluster={clusterConfig之一}访问
  appConfig: fy-admin-api,fy-admin-ui    # 配置Consul中注册的serviceId列表，表明监控哪些服务
  clusterNameExpression: new String("default")
  # 1. clusterNameExpression指定集群名称，默认表达式appName；此时：turbine.aggregator.clusterConfig需要配置想要监控的应用名称
  # 2. 当clusterNameExpression: default时，turbine.aggregator.clusterConfig可以不写，因为默认就是default
server:
  port: 8764 #启动端口
security:
  user:
    name: fy
    password: 123456
    role: USER