info:
  version: "@project.version@"
server:
  port: 9411
spring:
  application:
    name: "@project.artifactId@"
  sleuth:
    enabled: false
    sampler:
      percentage: 1.0
  cloud:
    stream:
      kafka: 
        binder:
          brokers: 192.168.113.19:9092
          zkNodes: 192.168.113.19:2181
  datasource:
    #schema:
    #- classpath:/zipkin.sql
    name: fy-zipkin
    url: jdbc:mysql://192.168.113.19:3306/fy-zipkin?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: mhaadmin
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    #initialize: true
    #continue-on-error: true
  rabbitmq:
    host: 192.168.113.18
    port: 35672
    username: admin
    password: Rabbit_fy_123
    virtual-host: /
#zipkin:
#  storage:
#    type: mysql
    
zipkin:
  self-tracing:
    enabled: false
    sample-rate: 1.0
  storage:
    type: elasticsearch
    elasticsearch:
      hosts: ${ES_HOSTS:192.168.113.20}
      index: ${ES_INDEX:zipkin}
      date-separator: ${ES_DATE_SEPARATOR:.}
      index-shards: ${ES_INDEX_SHARDS:1}
      index-replicas: ${ES_INDEX_REPLICAS:1}
#      username: ${ES_USERNAME:elastic}
#      password: ${ES_PASSWORD:changeme}
ui.logs-url: ${:192.168.113.20:5601/app/kibana#/discover?_a=(index:'filebeat-*',query:(language:lucene,query:'{traceId}'))}

##zip的数据库表    
##https://github.com/openzipkin/zipkin/blob/master/zipkin-storage/mysql/src/main/resources/mysql.sql