logging:
  level:
    tk.mybatis: DEBUG
    com.tencloud.lux.security.admin: DEBUG
info:
  version: "@project.version@"
spring:
  application:
    name: "@project.artifactId@"
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: NON_NULL
###MQ用来处理zipkin日志追踪
#  rabbitmq:
#    host: 192.168.113.18
#    port: 35672
#    username: admin
#    password: Rabbit_fy_123
#    virtual-host: /
  datasource:
      name: test
      url: jdbc:mysql://192.168.113.19:3306/ag_admin?useUnicode=true&characterEncoding=UTF8
      username: mhaadmin
      password: 123456
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
mybatis:
  basepackage: com.tencloud.lux.security.admin.mapper
  xmlLocation: classpath:mapper/**/*.xml

server:
    port: 8762
swagger:
  basepackage: com.tencloud.lux.security.admin
  service:
    name: Admin Back
    description: Admin Back后端服务
    developer: 老A
auth:
  serviceId: lux-auth
  user:
    token-header: Authorization
    pub-key:
      path: jwt/pub.key
  client:
    id: lux-admin
    secret: 123456
    token-header: client-token
    pub-key:
      path: client/pub.key
#redis-cache 相关
redis:
  pool:
    maxActive: 300
    maxIdle: 100
    maxWait: 1000
  host: 192.168.113.18
  port: 6379
  password: hhly_new_pass
  timeout: 2000
  # 服务或应用名
  sysName: lux-admin
  enable: true
  database: 0
hystrix:
  metrics:
    enabled: true
feign:
  hystrix:
    enabled: true   ##需要开启此配置，不然不生效