spring:
    application:
        name: admin-gate
    thymeleaf:
        mode: LEGACYHTML5
        cache: false
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: NON_NULL
    rabbitmq:
        host: 192.168.113.18
        port: 35672
        username: admin
        password: Rabbit_fy_123
        virtual-host: /
    redis:
        cluster:
            #nodes: 192.168.113.18:6379,192.168.113.18:6380,192.168.113.19:6379,192.168.113.19:6380,192.168.113.20:6379,192.168.113.20:6380 
            nodes:
            - 192.168.113.18:6379
            - 192.168.113.18:6380
            - 192.168.113.19:6379
            - 192.168.113.19:6380
            - 192.168.113.20:6379
            - 192.168.113.20:6380
        password: hhly_new_pass
        timeout: 20000
        pool:
            max-active: 8
            max-idle: 8
            min-idle: 0
            #max-wait: -1
server:
    port: 8765 #启动端口
#
zuul:
  ignored-services: "*"
  sensitive-headers:
  prefix: /api #为zuul设置一个公共的前缀
  ratelimit: # 网关限流
    key-prefix: gate_rate
    enabled: true
    repository: REDIS #REDIS, JPA, IN_MEMORY
    behind-proxy: true
    default-policy: #optional - will apply unless specific policy exists
      limit: 10
      refresh-interval: 60 #default value (in seconds)
      type: #optional
        - user
        - origin
        - url
  routes:
    back:
      path: /admin/**
      serviceId: lux-admin

    auth:
      path: /auth/**
      serviceId: lux-auth

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false


hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000


gate:
  ignore:
    startWith: /static,/auth/jwt
    contain: .
  oauth:
    prefix: /jwt
  jwt:
    secret: Xe*g@1jda
    expiration: 7200
    header: access-token

auth:
  serviceId: lux-auth
  user:
    token-header: Authorization
    pub-key:
      path: jwt/pub.key
  client:
    token-header: client-token
    id: lux-gate  #不填则默认读取spring.application.name
    secret: 123456
    pub-key:
      path: client/pub.key

